// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmuvK1aAeiPxNNVX3Zd7ZfCTmw1ON_OvM',
    appId: '1:258969253928:web:3405dc09d1625b53f25d1d',
    messagingSenderId: '258969253928',
    projectId: 'life-storybook-megha',
    authDomain: 'life-storybook-megha.firebaseapp.com',
    storageBucket: 'life-storybook-megha.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVY5pqlvStJslHpzsbddSY3cyCx4XXey8',
    appId: '1:258969253928:android:a343b7148d6b4956f25d1d',
    messagingSenderId: '258969253928',
    projectId: 'life-storybook-megha',
    storageBucket: 'life-storybook-megha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7vbBzdcx_LHEhjWt1YfU-RG-GIOEyY9U',
    appId: '1:258969253928:ios:5e377a443cefd298f25d1d',
    messagingSenderId: '258969253928',
    projectId: 'life-storybook-megha',
    storageBucket: 'life-storybook-megha.firebasestorage.app',
    iosBundleId: 'com.example.lifestorybook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7vbBzdcx_LHEhjWt1YfU-RG-GIOEyY9U',
    appId: '1:258969253928:ios:5e377a443cefd298f25d1d',
    messagingSenderId: '258969253928',
    projectId: 'life-storybook-megha',
    storageBucket: 'life-storybook-megha.firebasestorage.app',
    iosBundleId: 'com.example.lifestorybook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmuvK1aAeiPxNNVX3Zd7ZfCTmw1ON_OvM',
    appId: '1:258969253928:web:6ac6eb372ffe826ef25d1d',
    messagingSenderId: '258969253928',
    projectId: 'life-storybook-megha',
    authDomain: 'life-storybook-megha.firebaseapp.com',
    storageBucket: 'life-storybook-megha.firebasestorage.app',
  );
}
